/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message.RecipientType;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JRootPane;

/**
 *
 * @author MAYUR_DEBU
 */
    
public class ForgotForm extends javax.swing.JFrame {

    /**
     * Creates new form ForgotForm
     */
    
    int counter=1;
   
    public void jmail()
    {
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", 465);
        props.put("mail.smtp.user", "mayurmanoharpatil973@gmail.com");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.debug", "true");
        props.put("mail.smtp.socketFactory.port", 465);
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback", "false"); 
         
        try {
            
            Class.forName("com.mysql.jdbc.Driver");       
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","student");
            String query = "select Pass from Forgot where Email LIKE '"+jTextFieldEmailAdd.getText().trim()+"'";
            PreparedStatement statmnt = con.prepareStatement(query);
            ResultSet result = statmnt.executeQuery();     
            
            if (result.next())
            {   
                
                String fetchedPassword = result.getString("Pass");               
                Session session = Session.getDefaultInstance(props, null);//session intializing over internet inorder to send message
                session.setDebug(true);//session execution started
                MimeMessage message = new MimeMessage(session);
                message.setText("Your password is " + fetchedPassword+".");
                message.setSubject("Password Recovery");
                message.setFrom(new InternetAddress("mayurmanoharpatil973@gmail.com"));
                message.addRecipient(RecipientType.TO, new InternetAddress(jTextFieldEmailAdd.getText().trim()));//trim the trailing and a leading spaces
                message.saveChanges();
                Transport transport = session.getTransport("smtp");
                transport.connect("smtp.gmail.com", "mayurmanoharpatil973@gmail.com", "mayurpatil1999");
                transport.sendMessage(message, message.getAllRecipients());
                transport.close();
                // jLabelResponse.setText("Sending"); 
                jLabelResponse.setText("Your password is mailed to you");         
            }
            else
            {
                jLabelResponse.setText("Enter Correct Email ID");
            }
        } catch (Exception e) {
            e.printStackTrace();  
            jLabelResponse.setText("Email Address not found");
            counter=1;
            jTextFieldEmailAdd.setText("Email ID");
        }  
    }
    public ForgotForm() throws ClassNotFoundException, SQLException {
        super("Forgot Password");
      //  conn=javaconnect.connectDB();
         setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        
        initComponents();
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmailAdd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jLabelResponse = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 242, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Forgot Password?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 239, 33));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.darkGray);
        jLabel2.setText("We will email you your password.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 23));

        jTextFieldEmailAdd.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldEmailAdd.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldEmailAdd.setForeground(java.awt.Color.gray);
        jTextFieldEmailAdd.setText("Email ID");
        jTextFieldEmailAdd.setBorder(null);
        jTextFieldEmailAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldEmailAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEmailAddMouseClicked(evt);
            }
        });
        jPanel1.add(jTextFieldEmailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 290, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Just remembered?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 90, 22));
        jLabel5.setText(" Log in");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText(" Instead.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 80, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Don't have an account?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 170, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(231, 90, 22));
        jLabel8.setText("Register with us.");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 30));

        jButtonSend.setBackground(new java.awt.Color(231, 90, 22));
        jButtonSend.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSend.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSend.setText("SEND");
        jButtonSend.setBorder(null);
        jButtonSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSendMouseClicked(evt);
            }
        });
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        jButtonSend.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonSendPropertyChange(evt);
            }
        });
        jButtonSend.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jButtonSendVetoableChange(evt);
            }
        });
        jPanel2.add(jButtonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 280, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 260));
        jPanel1.add(jLabelResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/close.png"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        LoginForm lf = null;
        try {
            lf = new LoginForm();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ForgotForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ForgotForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        RegisterForm rff = null;
        try {
            rff = new RegisterForm();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ForgotForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ForgotForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        rff.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
      //  jLabelResponse.setVisible(true);
        
            
            jmail();
            /* Properties props = new Properties();
            
            props.put("mail.smtp.host", "smtp.gmail.com");       
            props.put("mail.smtp.port", 465);
            props.put("mail.smtp.user", "mayurmanoharpatil973@gmail.com");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.debug", "true");
            props.put("mail.smtp.socketFactory.port", 465);
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            props.put("mail.smtp.socketFactory.fallback", "false");
            
            try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","student");
            String query = "select Pass from Forgot where Email LIKE '"+jTextFieldEmailAdd.getText().trim()+"'";
            PreparedStatement statmnt = con.prepareStatement(query);
            ResultSet result = statmnt.executeQuery();     
            
            if (result.next())
            {
            
            String fetchedPassword = result.getString("Pass");
            Session session = Session.getDefaultInstance(props, null);//session intializing over internet inorder to send message
            session.setDebug(true);
            MimeMessage message = new MimeMessage(session);
            message.setText("Your password is " + fetchedPassword+".");
            message.setSubject("Password Recovery");
            message.setFrom(new InternetAddress("mayurmanoharpatil973@gmail.com"));
            message.addRecipient(RecipientType.TO, new InternetAddress(jTextFieldEmailAdd.getText().trim()));//trim the trailing and a leading spaces
            message.saveChanges();
            Transport transport = session.getTransport("smtp");
            transport.connect("smtp.gmail.com", "mayurmanoharpatil973@gmail.com", "mayurpatil1999");
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            // jLabelResponse.setText("Sending");
            jLabelResponse.setText("Your password is mailed to you");         
            }
            else
            {
            jLabelResponse.setText("Enter Correct Email ID");
            }
            } catch (Exception e) {
            e.printStackTrace();  
            jLabelResponse.setText("Email Address not found");
            counter=1;
            jTextFieldEmailAdd.setText("Email ID");
            }  */
       
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextFieldEmailAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailAddMouseClicked
        // TODO add your handling code here:
        if(counter==1)
        {
            jTextFieldEmailAdd.setText("");
            counter++;
        }
    }//GEN-LAST:event_jTextFieldEmailAddMouseClicked

    private void jButtonSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSendMouseClicked
        // TODO add your handling code here:
       // jLabelResponse.setText("SENDING");
    }//GEN-LAST:event_jButtonSendMouseClicked

    private void jButtonSendPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonSendPropertyChange
        // TODO add your handling code here:
        // jLabelResponse.setText("SENDING");
    }//GEN-LAST:event_jButtonSendPropertyChange

    private void jButtonSendVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jButtonSendVetoableChange
        // TODO add your handling code here:
        // jLabelResponse.setText("SENDING");
    }//GEN-LAST:event_jButtonSendVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ForgotForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ForgotForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ForgotForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabelResponse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEmailAdd;
    // End of variables declaration//GEN-END:variables
}
